# Generated by Django 4.1.7 on 2023-03-25 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_api.ticket'),
        ),
    ]
